#!/usr/bin/zsh
# -*- coding: utf-8 -*-
### ------------------------------------
### merge gff results generated by annotation pipeline/software
### ------------------------------------

# Get gffdir from input
usage() {
	echo "Usage:\tzsh /pathToscript/mergegff.sh -d <DirIncludeGFFs>"
}
while {getopts d:h arg} {
	case $arg {
		(d)
		gffdir=$OPTARG
		d=$arg
		# Test if the gffdir exists.
		if [[ -d $gffdir ]] {
			echo "Your gffdir is $gffdir"
		} else { 
				echo "The directory that you specified is not exist, please specify the correct path."
				exit 
		}
		;;
		(?)
		echo "Wrong option!"
		usage
		;;
	}
}

#  Test if the -d option is provided.
if [[ -z $d ]] {
	echo "You must use -d to specify the directory that contains all the gff files that you want to merge."
	exit
}

# Merge all gff to a big gff
rmexist() {
	if [[ -f $1 ]] {
		rm -rf $1
	}
}
rmexist $gffdir/merged.gff
ls $gffdir/*gff | while read gff
do
	print "Proccessing $gff..."
	grep -v "^#" $gff >> $gffdir/merged.gff
done && print "Successfully merged gff files!"
