#!/usr/bin/zsh
# -*- coding: utf-8 -*-
### ------------------------------------
### merge gff results generated by annotation pipeline/software
### ------------------------------------

# Get gffdir from input
usage() {
	echo "zsh /pathToscript/mergegff.sh -d <DirIncludeGFFs>"
}
while {getopts d: arg} {
	case $arg {
		(d)
		gffdir=$OPTARG
		d=$arg
		# Test if the gffdir exists.
		if [[ -d $gffdir ]] {
			echo "Your gffdir is $gffdir"
		} else { 
				echo "The directory that you specified is not exist, please specify the correct path."
				exit 
		}
		;;
		(?)
		echo "Wrong option!"
		;;
	}
}

#  Test if the -d option is provided.
if [[ -z $d ]] {
	echo "You must use -d to specify the directory that contains all the gff files that you want to merge."
	exit
}

# Merge all gff to a big gff
rmexist() {
	if [[ -f $1 ]] {
		rm -rf $1
	}
}
rmexist $gffdir/merged.gff
rmexist $gffdir/sortedmerged.gff
rmexist $gffdir/filtermerged.gff

ls $gffdir/*gff | while read gff
do
	print "Proccessing $gff..."
	grep -v "^#" $gff >> $gffdir/merged.gff
done && print "Successfully merged gff files!"

# sort gff
## Get a sorted id array that contains only the rows whose feature is gene 
id_sorted=`gawk '$3=="gene"{print $0}' $gffdir/merged.gff |
	sort -t $'\t' -k 1,1 -k 7,7 -k 4n,4 -k 5n,5`
## Use awk and srotedIDarray to get a sorted gff file
gawk -v arr=$id_sorted '
BEGIN{
split(arr,id_sorted,"\n")
RS="\n"
FS="\t"
OFS="\t"
ORS="\n"
}
$3=="gene"{
	recs[id]=id"\n"lines
	id=$0
	lines=""
}
$3!="gene"{
	lines=lines"\n"$0
}
END{
recs[id]=id+"\n"+lines
for (id in id_sorted){
	# print recs[id]
	print recs[id_sorted[id]]
}
}
' $gffdir/merged.gff | sed '/^\s*$/d' > $gffdir/sortedmerged.gff


# Exclude overlap records of sorted gff
gawk 'BEGIN{
RS="\n"
FS="\t"
flag=1
}
$3=="gene"{
if(!start[$1","$7]){
	start[$1","$7]=$4
	end[$1","$7]=$5
	flag=1
	print $0
}
else{
	s=start[$1","$7]
	e=end[$1","$7]
	if((s<=$4&&$4<=e)||(s<=$5&&$5<=$e)){
		flag=0
	}
	else{
		start[$1","$7]=$4
		end[$1","$7]=$5
		flag=1
		print $0
	}
}
}
$3!="gene"&&flag==1{print $0}
' $gffdir/sortedmerged.gff > $gffdir/filtermerged.gff

